# Aula 1

In [22]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [4]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [5]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [6]:
rows, columns = df.shape
print(f"Linhas: {rows};\nColunas: {columns}.")

Linhas: 133349;
Colunas: 11.

In [7]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='str')

In [8]:
traducao = {
    "work_year": "ano_de_trabalho",
    "experience_level": "nivel_de_experiencia",
    "employment_type": "tipo_de_emprego",
    "job_title": "cargo",
    "salary": "salario",
    "salary_currency": "moeda_do_salario",
    "salary_in_usd": "salario_em_usd",
    "employee_residence": "residencia_do_funcionario",
    "remote_ratio": "percentual_remoto",
    "company_location": "localizacao_da_empresa",
    "company_size": "tamanho_da_empresa",
}

df.rename(columns=traducao, inplace=True)

In [9]:
traducao = {
    "SE": "senior",
    "MI": "pleno",
    "EN": "junior",
    "EX": "executivo"
}
df["nivel_de_experiencia"] = df["nivel_de_experiencia"].astype(str).replace(traducao)

In [10]:
df["tipo_de_emprego"] = df["tipo_de_emprego"].astype(str).replace({
    "FT": "integral",
    "PT": "parcial",
    "FL": "freelancer",
    "CT": "contrato"
})

In [11]:
df["tamanho_da_empresa"] = df["tamanho_da_empresa"].astype(str).replace({
    "S": "pequena",
    "M": "média",
    "L": "grande"
})

In [12]:
df["percentual_remoto"] = df["percentual_remoto"].replace(
    {100: "remoto", 50: "parcial", 0: "presencial"}
)

In [13]:
df.describe(include="all")

,ano_de_trabalho,nivel_de_experiencia,tipo_de_emprego,cargo,salario,moeda_do_salario,salario_em_usd,residencia_do_funcionario,percentual_remoto,localizacao_da_empresa,tamanho_da_empresa
count,133339.000000,133349,133349,133349,1.333490e+05,133349,133349.000000,133349,133349,133349,133349
unique,NaN,4,4,390,NaN,26,NaN,102,3,95,3
top,NaN,senior,integral,Data Scientist,NaN,USD,NaN,US,presencial,US,média
freq,NaN,77241,132563,17314,NaN,126140,NaN,119579,105312,119641,129561
mean,2024.358770,NaN,NaN,NaN,1.632833e+05,NaN,157617.272098,NaN,NaN,NaN,NaN
std,0.680627,NaN,NaN,NaN,2.173860e+05,NaN,74288.363097,NaN,NaN,NaN,NaN
min,2020.000000,NaN,NaN,NaN,1.400000e+04,NaN,15000.000000,NaN,NaN,NaN,NaN
25%,2024.000000,NaN,NaN,NaN,1.060200e+05,NaN,106000.000000,NaN,NaN,NaN,NaN
50%,2024.000000,NaN,NaN,NaN,1.470000e+05,NaN,146206.000000,NaN,NaN,NaN,NaN
75%,2025.000000,NaN,NaN,NaN,1.990000e+05,NaN,198000.000000,NaN,NaN,NaN,NaN
max,2025.000000,NaN,NaN,NaN,3.040000e+07,NaN,800000.000000,NaN,NaN,NaN,NaN

# Aula 2

In [14]:
df.head()

,ano_de_trabalho,nivel_de_experiencia,tipo_de_emprego,cargo,salario,moeda_do_salario,salario_em_usd,residencia_do_funcionario,percentual_remoto,localizacao_da_empresa,tamanho_da_empresa
0,2025.0,senior,integral,Solutions Engineer,214000,USD,214000,US,remoto,US,média
1,2025.0,senior,integral,Solutions Engineer,136000,USD,136000,US,remoto,US,média
2,2025.0,pleno,integral,Data Engineer,158800,USD,158800,AU,presencial,AU,média
3,2025.0,pleno,integral,Data Engineer,139200,USD,139200,AU,presencial,AU,média
4,2025.0,junior,integral,Data Engineer,90000,USD,90000,US,presencial,US,média

In [15]:
df["ano_de_trabalho"].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [16]:
df = df[~df["ano_de_trabalho"].isna()]

In [23]:
df["ano_de_trabalho"] = df["ano_de_trabalho"].astype(np.uint16)
df.head()

,ano_de_trabalho,nivel_de_experiencia,tipo_de_emprego,cargo,salario,moeda_do_salario,salario_em_usd,residencia_do_funcionario,percentual_remoto,localizacao_da_empresa,tamanho_da_empresa
0,2025,senior,integral,Solutions Engineer,214000,USD,214000,US,remoto,US,média
1,2025,senior,integral,Solutions Engineer,136000,USD,136000,US,remoto,US,média
2,2025,pleno,integral,Data Engineer,158800,USD,158800,AU,presencial,AU,média
3,2025,pleno,integral,Data Engineer,139200,USD,139200,AU,presencial,AU,média
4,2025,junior,integral,Data Engineer,90000,USD,90000,US,presencial,US,média