In [34]:
import pandas as pd

In [35]:
df = pd.DataFrame({
    "nome": ["Ana", "Bruno", "Carlos", "Daniel", "Emanuele", "Fernando", "Gabriela", "Henrique", "Isabela", "João", "Karla", "Lucas"],
    "cidade": ["São Paulo", None, "Belo Horizonte", "Manacapuru", "Porto Alegre", None, "Fortaleza", "Brasília", None, "Recife", "Florianópolis", None],
    "estado": ["SP", "RJ", None, "AM", "RS", None, "CE", "DF", "PE", None, "SC", "MG"]
})
df

        nome          cidade estado
0        Ana       São Paulo     SP
1      Bruno             NaN     RJ
2     Carlos  Belo Horizonte    NaN
3     Daniel      Manacapuru     AM
4   Emanuele    Porto Alegre     RS
5   Fernando             NaN    NaN
6   Gabriela       Fortaleza     CE
7   Henrique        Brasília     DF
8    Isabela             NaN     PE
9       João          Recife    NaN
10     Karla   Florianópolis     SC
11     Lucas             NaN     MG

In [36]:
df["cidade_p"] = df["cidade"].fillna("não informado")
df["estado_p"] = df["estado"].fillna("não informado")

In [37]:
# df_limpo = df.query("cidade.notna() and estado.notna()")
df_limpo = df.dropna()

In [38]:
df_limpo

        nome         cidade estado       cidade_p estado_p
0        Ana      São Paulo     SP      São Paulo       SP
3     Daniel     Manacapuru     AM     Manacapuru       AM
4   Emanuele   Porto Alegre     RS   Porto Alegre       RS
6   Gabriela      Fortaleza     CE      Fortaleza       CE
7   Henrique       Brasília     DF       Brasília       DF
10     Karla  Florianópolis     SC  Florianópolis       SC